# Diabetes.ipynb

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.pipeline import Pipeline
import xgboost as xbg
import os 
import sys

In [2]:
cwd = os.getcwd()

print(cwd)

/Users/saikeerthan/NYP-AI/Year3/AI_Application/Diabetes

In [3]:
df = os.path.join(cwd, "data/diabetes_dataset00.csv")

if df:
    print("YES")
else: 
    print("NO")

YES

In [4]:
df = pd.read_csv(df)

df

,Target,Genetic Markers,Autoantibodies,Family History,Environmental Factors,Insulin Levels,Age,BMI,Physical Activity,Dietary Habits,...,Pulmonary Function,Cystic Fibrosis Diagnosis,Steroid Use History,Genetic Testing,Neurological Assessments,Liver Function Tests,Digestive Enzyme Levels,Urine Test,Birth Weight,Early Onset Symptoms
0,Steroid-Induced Diabetes,Positive,Negative,No,Present,40,44,38,High,Healthy,...,76,No,No,Positive,3,Normal,56,Ketones Present,2629,No
1,Neonatal Diabetes Mellitus (NDM),Positive,Negative,No,Present,13,1,17,High,Healthy,...,60,Yes,No,Negative,1,Normal,28,Glucose Present,1881,Yes
2,Prediabetic,Positive,Positive,Yes,Present,27,36,24,High,Unhealthy,...,80,Yes,No,Negative,1,Abnormal,55,Ketones Present,3622,Yes
3,Type 1 Diabetes,Negative,Positive,No,Present,8,7,16,Low,Unhealthy,...,89,Yes,No,Positive,2,Abnormal,60,Ketones Present,3542,No
4,Wolfram Syndrome,Negative,Negative,Yes,Present,17,10,17,High,Healthy,...,41,No,No,Positive,1,Normal,24,Protein Present,1770,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,Steroid-Induced Diabetes,Negative,Negative,Yes,Present,24,38,35,High,Unhealthy,...,71,Yes,Yes,Positive,2,Abnormal,34,Normal,2575,No
69996,LADA,Positive,Positive,No,Absent,21,51,31,Low,Unhealthy,...,82,Yes,Yes,Negative,1,Abnormal,58,Ketones Present,3002,No
69997,Type 1 Diabetes,Positive,Negative,No,Absent,18,11,15,Low,Unhealthy,...,77,Yes,Yes,Positive,2,Normal,53,Protein Present,3593,No
69998,Cystic Fibrosis-Related Diabetes (CFRD),Positive,Negative,No,Absent,32,30,24,High,Healthy,...,70,No,No,Positive,1,Abnormal,35,Ketones Present,2592,Yes
69999,LADA,Positive,Positive,Yes,Absent,27,41,28,Moderate,Healthy,...,84,No,Yes,Negative,2,Abnormal,64,Ketones Present,3593,Yes

In [5]:
df.isnull().sum()

Target                           0
Genetic Markers                  0
Autoantibodies                   0
Family History                   0
Environmental Factors            0
Insulin Levels                   0
Age                              0
BMI                              0
Physical Activity                0
Dietary Habits                   0
Blood Pressure                   0
Cholesterol Levels               0
Waist Circumference              0
Blood Glucose Levels             0
Ethnicity                        0
Socioeconomic Factors            0
Smoking Status                   0
Alcohol Consumption              0
Glucose Tolerance Test           0
History of PCOS                  0
Previous Gestational Diabetes    0
Pregnancy History                0
Weight Gain During Pregnancy     0
Pancreatic Health                0
Pulmonary Function               0
Cystic Fibrosis Diagnosis        0
Steroid Use History              0
Genetic Testing                  0
Neurological Assessments         0
Liver Function Tests             0
Digestive Enzyme Levels          0
Urine Test                       0
Birth Weight                     0
Early Onset Symptoms             0
dtype: int64

In [6]:
# print a summary of each column 


executive_summary = pd.DataFrame({
    "columns": df.columns,
    "num_unique": [df[c].nunique(dropna=False) for c in df.columns],
    "samples": [df[c].unique()[:5] for c in df.columns]
})

In [7]:
executive_summary

,columns,num_unique,samples
0,Target,13,"[Steroid-Induced Diabetes, Neonatal Diabetes M..."
1,Genetic Markers,2,"[Positive, Negative]"
2,Autoantibodies,2,"[Negative, Positive]"
3,Family History,2,"[No, Yes]"
4,Environmental Factors,2,"[Present, Absent]"
5,Insulin Levels,45,"[40, 13, 27, 8, 17]"
6,Age,80,"[44, 1, 36, 7, 10]"
7,BMI,28,"[38, 17, 24, 16, 26]"
8,Physical Activity,3,"[High, Low, Moderate]"
9,Dietary Habits,2,"[Healthy, Unhealthy]"
10,Blood Pressure,90,"[124, 73, 121, 100, 103]"
11,Cholesterol Levels,200,"[201, 121, 185, 151, 146]"
12,Waist Circumference,35,"[50, 24, 36, 29, 33]"
13,Blood Glucose Levels,220,"[168, 178, 105, 121, 289]"
14,Ethnicity,2,"[Low Risk, High Risk]"
15,Socioeconomic Factors,3,"[Medium, High, Low]"
16,Smoking Status,2,"[Smoker, Non-Smoker]"
17,Alcohol Consumption,3,"[High, Moderate, Low]"
18,Glucose Tolerance Test,2,"[Normal, Abnormal]"
19,History of PCOS,2,"[No, Yes]"
20,Previous Gestational Diabetes,2,"[No, Yes]"
21,Pregnancy History,2,"[Normal, Complications]"
22,Weight Gain During Pregnancy,40,"[18, 8, 15, 12, 2]"
23,Pancreatic Health,90,"[36, 26, 56, 49, 10]"
24,Pulmonary Function,60,"[76, 60, 80, 89, 41]"
25,Cystic Fibrosis Diagnosis,2,"[No, Yes]"
26,Steroid Use History,2,"[No, Yes]"
27,Genetic Testing,2,"[Positive, Negative]"
28,Neurological Assessments,3,"[3, 1, 2]"
29,Liver Function Tests,2,"[Normal, Abnormal]"
30,Digestive Enzyme Levels,90,"[56, 28, 55, 60, 24]"
31,Urine Test,4,"[Ketones Present, Glucose Present, Protein Pre..."
32,Birth Weight,3000,"[2629, 1881, 3622, 3542, 1770]"
33,Early Onset Symptoms,2,"[No, Yes]"

In [8]:
# List of placeholders to check for
placeholders = ["unknown", "Unknown", "UNK", "Not Available", "N/A", "na", "?", "-", "missing"]

# Create a summary dictionary
unknown_summary = {}

for col in df.columns:
    count = 0
    for placeholder in placeholders:
        count += (df[col].astype(str).str.strip().str.lower() == placeholder.lower()).sum()
    if count > 0:
        unknown_summary[col] = count

# Show summary
if unknown_summary:
    print("Columns with unknown values and their counts:")
    for col, cnt in unknown_summary.items():
        print(f"{col}: {cnt}")
else:
    print("No 'unknown' values found in any column!")

No 'unknown' values found in any column!

In [9]:
# Separate columns by type based on your summary
numerical_cols = [
    'Insulin Levels', 'Age', 'BMI', 'Blood Pressure', 'Cholesterol Levels',
    'Waist Circumference', 'Blood Glucose Levels', 'Birth Weight',
    'Weight Gain During Pregnancy', 'Pancreatic Health', 'Pulmonary Function',
    'Digestive Enzyme Levels'
]
# If you want, you can add more columns with many unique values

print("=== Outlier Summary by Column ===\n")
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)][col]
    print(f"{col}: {len(outliers)} outliers")
    # Optionally: print extreme values
    # print(outliers.sort_values().head(3))
    # print(outliers.sort_values(ascending=False).head(3))
print("\n=== Done ===")

=== Outlier Summary by Column ===

Insulin Levels: 0 outliers
Age: 0 outliers
BMI: 0 outliers
Blood Pressure: 0 outliers
Cholesterol Levels: 0 outliers
Waist Circumference: 522 outliers
Blood Glucose Levels: 0 outliers
Birth Weight: 0 outliers
Weight Gain During Pregnancy: 0 outliers
Pancreatic Health: 0 outliers
Pulmonary Function: 1206 outliers
Digestive Enzyme Levels: 0 outliers

=== Done ===

In [10]:
categorical_cols = [
    'Genetic Markers', 'Autoantibodies', 'Family History', 'Environmental Factors', 
    'Physical Activity', 'Dietary Habits', 'Ethnicity', 'Socioeconomic Factors', 
    'Smoking Status', 'Alcohol Consumption', 'Glucose Tolerance Test', 
    'History of PCOS', 'Previous Gestational Diabetes', 'Pregnancy History', 
    'Cystic Fibrosis Diagnosis', 'Steroid Use History', 'Genetic Testing', 
    'Neurological Assessments', 'Liver Function Tests', 'Urine Test', 
    'Early Onset Symptoms'
]
for col in categorical_cols:
    print(f"\n{col} value counts:")
    print(df[col].value_counts())

Genetic Markers value counts:
Genetic Markers
Positive    35101
Negative    34899
Name: count, dtype: int64

Autoantibodies value counts:
Autoantibodies
Negative    35058
Positive    34942
Name: count, dtype: int64

Family History value counts:
Family History
Yes    35168
No     34832
Name: count, dtype: int64

Environmental Factors value counts:
Environmental Factors
Absent     35088
Present    34912
Name: count, dtype: int64

Physical Activity value counts:
Physical Activity
Moderate    23427
Low         23348
High        23225
Name: count, dtype: int64

Dietary Habits value counts:
Dietary Habits
Healthy      35020
Unhealthy    34980
Name: count, dtype: int64

Ethnicity value counts:
Ethnicity
Low Risk     35018
High Risk    34982
Name: count, dtype: int64

Socioeconomic Factors value counts:
Socioeconomic Factors
Medium    23413
High      23304
Low       23283
Name: count, dtype: int64

Smoking Status value counts:
Smoking Status
Smoker        35045
Non-Smoker    34955
Name: count, dtype: int64

Alcohol Consumption value counts:
Alcohol Consumption
Low         23411
Moderate    23343
High        23246
Name: count, dtype: int64

Glucose Tolerance Test value counts:
Glucose Tolerance Test
Abnormal    35278
Normal      34722
Name: count, dtype: int64

History of PCOS value counts:
History of PCOS
No     35101
Yes    34899
Name: count, dtype: int64

Previous Gestational Diabetes value counts:
Previous Gestational Diabetes
Yes    35035
No     34965
Name: count, dtype: int64

Pregnancy History value counts:
Pregnancy History
Normal           35270
Complications    34730
Name: count, dtype: int64

Cystic Fibrosis Diagnosis value counts:
Cystic Fibrosis Diagnosis
No     35135
Yes    34865
Name: count, dtype: int64

Steroid Use History value counts:
Steroid Use History
No     35142
Yes    34858
Name: count, dtype: int64

Genetic Testing value counts:
Genetic Testing
Positive    35315
Negative    34685
Name: count, dtype: int64

Neurological Assessments value counts:
Neurological Assessments
2    34933
1    24388
3    10679
Name: count, dtype: int64

Liver Function Tests value counts:
Liver Function Tests
Normal      35019
Abnormal    34981
Name: count, dtype: int64

Urine Test value counts:
Urine Test
Protein Present    17628
Normal             17528
Ketones Present    17422
Glucose Present    17422
Name: count, dtype: int64

Early Onset Symptoms value counts:
Early Onset Symptoms
No     35059
Yes    34941
Name: count, dtype: int64

In [11]:
for col in ["Waist Circumference", "Pulmonary Function"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    print(f"\n{col} - min: {df[col].min()}, max: {df[col].max()}, lower: {lower}, upper: {upper}")
    print(df[col].describe())

Waist Circumference - min: 20, max: 54, lower: 16.5, upper: 52.5
count    70000.000000
mean        35.051657
std          6.803461
min         20.000000
25%         30.000000
50%         34.000000
75%         39.000000
max         54.000000
Name: Waist Circumference, dtype: float64

Pulmonary Function - min: 30, max: 89, lower: 39.0, upper: 103.0
count    70000.000000
mean        70.264671
std         11.965600
min         30.000000
25%         63.000000
50%         72.000000
75%         79.000000
max         89.000000
Name: Pulmonary Function, dtype: float64

In [12]:
# Calculate value counts for the target variable
class_counts = df['Target'].value_counts().sort_values(ascending=False)

# Plotly bar plot
fig = px.bar(
    x=class_counts.index,
    y=class_counts.values,
    labels={'x': 'Diabetes Type', 'y': 'Count'},
    title='Distribution of Diabetes Types in Dataset',
    text=class_counts.values
)
fig.update_traces(textposition='outside')
fig.update_layout(xaxis_tickangle=30)
fig.show()

In [13]:
# Plot percentage distribution with Plotly
class_percent = 100 * class_counts / class_counts.sum()
fig = px.bar(
    x=class_percent.index,
    y=class_percent.values,
    labels={'x': 'Diabetes Type', 'y': 'Percentage (%)'},
    title='Percentage Distribution of Diabetes Types in Dataset',
    text=class_percent.round(2).astype(str) + '%'
)
fig.update_traces(textposition='inside')
fig.update_layout(xaxis_tickangle=30)
fig.show()

# ML Modelling

In [14]:
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

## XGBOOST

### First Round of Training

In [15]:
# 2. Define features
target_col = 'Target'
categorical_cols = [
    'Genetic Markers', 'Autoantibodies', 'Family History', 'Environmental Factors', 
    'Physical Activity', 'Dietary Habits', 'Ethnicity', 'Socioeconomic Factors', 
    'Smoking Status', 'Alcohol Consumption', 'Glucose Tolerance Test', 
    'History of PCOS', 'Previous Gestational Diabetes', 'Pregnancy History', 
    'Cystic Fibrosis Diagnosis', 'Steroid Use History', 'Genetic Testing', 
    'Neurological Assessments', 'Liver Function Tests', 'Urine Test', 'Early Onset Symptoms'
]
numerical_cols = [
    'Insulin Levels', 'Age', 'BMI', 'Blood Pressure', 'Cholesterol Levels',
    'Waist Circumference', 'Blood Glucose Levels', 'Birth Weight',
    'Weight Gain During Pregnancy', 'Pancreatic Health', 'Pulmonary Function',
    'Digestive Enzyme Levels'
]
# Drop columns if you find any non-predictive (e.g., IDs)

In [16]:
# 3. Encode target variable
y = df[target_col].astype(str)
y_cat, y_labels = pd.factorize(y)  # Saves mapping for inverse transform

# 4. Encode categorical variables (OneHotEncoder, handle_unknown ensures no error)
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_cat = ohe.fit_transform(df[categorical_cols])

# 5. Combine with numerical features
X_num = df[numerical_cols].values
X = np.hstack([X_num, X_cat])

# 6. Train/val/test split (70/15/15 split)
X_temp, X_test, y_temp, y_test = train_test_split(X, y_cat, test_size=0.15, random_state=42, stratify=y_cat)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.1765, random_state=42, stratify=y_temp)
# 0.1765 * 0.85 ≈ 0.15 (so you get ~70/15/15 split)

In [17]:
# 7. Build and train XGBoost model (multiclass)
xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=8,
    objective='multi:softprob',
    num_class=len(y_labels),
    eval_metric='mlogloss',
    use_label_encoder=False,
    n_jobs=-1,
    random_state=42
)
xgb.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=True)

[0]	validation_0-mlogloss:2.08555
[1]	validation_0-mlogloss:1.80658
[2]	validation_0-mlogloss:1.60261
[3]	validation_0-mlogloss:1.44197

/Users/saikeerthan/NYP-AI/Year3/new_y3s1/lib/python3.11/site-packages/xgboost/training.py:183: UserWarning:

[20:11:50] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.

[4]	validation_0-mlogloss:1.31007
[5]	validation_0-mlogloss:1.19838
[6]	validation_0-mlogloss:1.10197
[7]	validation_0-mlogloss:1.01791
[8]	validation_0-mlogloss:0.94446
[9]	validation_0-mlogloss:0.87904
[10]	validation_0-mlogloss:0.82079
[11]	validation_0-mlogloss:0.76854
[12]	validation_0-mlogloss:0.72183
[13]	validation_0-mlogloss:0.67939
[14]	validation_0-mlogloss:0.64103
[15]	validation_0-mlogloss:0.60617
[16]	validation_0-mlogloss:0.57446
[17]	validation_0-mlogloss:0.54564
[18]	validation_0-mlogloss:0.51922
[19]	validation_0-mlogloss:0.49523
[20]	validation_0-mlogloss:0.47340
[21]	validation_0-mlogloss:0.45332
[22]	validation_0-mlogloss:0.43484
[23]	validation_0-mlogloss:0.41797
[24]	validation_0-mlogloss:0.40225
[25]	validation_0-mlogloss:0.38788
[26]	validation_0-mlogloss:0.37464
[27]	validation_0-mlogloss:0.36237
[28]	validation_0-mlogloss:0.35108
[29]	validation_0-mlogloss:0.34061
[30]	validation_0-mlogloss:0.33098
[31]	validation_0-mlogloss:0.32206
[32]	validation_0-mlogloss:0.31378
[33]	validation_0-mlogloss:0.30612
[34]	validation_0-mlogloss:0.29910
[35]	validation_0-mlogloss:0.29255
[36]	validation_0-mlogloss:0.28638
[37]	validation_0-mlogloss:0.28071
[38]	validation_0-mlogloss:0.27545
[39]	validation_0-mlogloss:0.27053
[40]	validation_0-mlogloss:0.26595
[41]	validation_0-mlogloss:0.26170
[42]	validation_0-mlogloss:0.25773
[43]	validation_0-mlogloss:0.25393
[44]	validation_0-mlogloss:0.25045
[45]	validation_0-mlogloss:0.24713
[46]	validation_0-mlogloss:0.24407
[47]	validation_0-mlogloss:0.24119
[48]	validation_0-mlogloss:0.23848
[49]	validation_0-mlogloss:0.23586
[50]	validation_0-mlogloss:0.23351
[51]	validation_0-mlogloss:0.23129
[52]	validation_0-mlogloss:0.22916
[53]	validation_0-mlogloss:0.22718
[54]	validation_0-mlogloss:0.22533
[55]	validation_0-mlogloss:0.22363
[56]	validation_0-mlogloss:0.22196
[57]	validation_0-mlogloss:0.22046
[58]	validation_0-mlogloss:0.21890
[59]	validation_0-mlogloss:0.21754
[60]	validation_0-mlogloss:0.21625
[61]	validation_0-mlogloss:0.21506
[62]	validation_0-mlogloss:0.21390
[63]	validation_0-mlogloss:0.21283
[64]	validation_0-mlogloss:0.21177
[65]	validation_0-mlogloss:0.21078
[66]	validation_0-mlogloss:0.20982
[67]	validation_0-mlogloss:0.20899
[68]	validation_0-mlogloss:0.20809
[69]	validation_0-mlogloss:0.20732
[70]	validation_0-mlogloss:0.20662
[71]	validation_0-mlogloss:0.20593
[72]	validation_0-mlogloss:0.20528
[73]	validation_0-mlogloss:0.20466
[74]	validation_0-mlogloss:0.20414
[75]	validation_0-mlogloss:0.20357
[76]	validation_0-mlogloss:0.20315
[77]	validation_0-mlogloss:0.20263
[78]	validation_0-mlogloss:0.20214
[79]	validation_0-mlogloss:0.20176
[80]	validation_0-mlogloss:0.20141
[81]	validation_0-mlogloss:0.20115
[82]	validation_0-mlogloss:0.20075
[83]	validation_0-mlogloss:0.20036
[84]	validation_0-mlogloss:0.19997
[85]	validation_0-mlogloss:0.19979
[86]	validation_0-mlogloss:0.19945
[87]	validation_0-mlogloss:0.19911
[88]	validation_0-mlogloss:0.19885
[89]	validation_0-mlogloss:0.19860
[90]	validation_0-mlogloss:0.19843
[91]	validation_0-mlogloss:0.19815
[92]	validation_0-mlogloss:0.19802
[93]	validation_0-mlogloss:0.19777
[94]	validation_0-mlogloss:0.19763
[95]	validation_0-mlogloss:0.19748
[96]	validation_0-mlogloss:0.19730
[97]	validation_0-mlogloss:0.19711
[98]	validation_0-mlogloss:0.19692
[99]	validation_0-mlogloss:0.19683
[100]	validation_0-mlogloss:0.19675
[101]	validation_0-mlogloss:0.19672
[102]	validation_0-mlogloss:0.19656
[103]	validation_0-mlogloss:0.19641
[104]	validation_0-mlogloss:0.19631
[105]	validation_0-mlogloss:0.19626
[106]	validation_0-mlogloss:0.19626
[107]	validation_0-mlogloss:0.19615
[108]	validation_0-mlogloss:0.19615
[109]	validation_0-mlogloss:0.19599
[110]	validation_0-mlogloss:0.19596
[111]	validation_0-mlogloss:0.19609
[112]	validation_0-mlogloss:0.19600
[113]	validation_0-mlogloss:0.19597
[114]	validation_0-mlogloss:0.19593
[115]	validation_0-mlogloss:0.19605
[116]	validation_0-mlogloss:0.19618
[117]	validation_0-mlogloss:0.19619
[118]	validation_0-mlogloss:0.19628
[119]	validation_0-mlogloss:0.19626
[120]	validation_0-mlogloss:0.19619
[121]	validation_0-mlogloss:0.19636
[122]	validation_0-mlogloss:0.19637
[123]	validation_0-mlogloss:0.19649
[124]	validation_0-mlogloss:0.19648
[125]	validation_0-mlogloss:0.19647
[126]	validation_0-mlogloss:0.19656
[127]	validation_0-mlogloss:0.19661
[128]	validation_0-mlogloss:0.19659
[129]	validation_0-mlogloss:0.19662
[130]	validation_0-mlogloss:0.19678
[131]	validation_0-mlogloss:0.19677
[132]	validation_0-mlogloss:0.19676
[133]	validation_0-mlogloss:0.19686
[134]	validation_0-mlogloss:0.19688
[135]	validation_0-mlogloss:0.19697
[136]	validation_0-mlogloss:0.19711
[137]	validation_0-mlogloss:0.19717
[138]	validation_0-mlogloss:0.19727
[139]	validation_0-mlogloss:0.19754
[140]	validation_0-mlogloss:0.19763
[141]	validation_0-mlogloss:0.19770
[142]	validation_0-mlogloss:0.19773
[143]	validation_0-mlogloss:0.19778
[144]	validation_0-mlogloss:0.19771
[145]	validation_0-mlogloss:0.19779
[146]	validation_0-mlogloss:0.19783
[147]	validation_0-mlogloss:0.19803
[148]	validation_0-mlogloss:0.19814
[149]	validation_0-mlogloss:0.19822
[150]	validation_0-mlogloss:0.19833
[151]	validation_0-mlogloss:0.19834
[152]	validation_0-mlogloss:0.19829
[153]	validation_0-mlogloss:0.19833
[154]	validation_0-mlogloss:0.19827
[155]	validation_0-mlogloss:0.19827
[156]	validation_0-mlogloss:0.19832
[157]	validation_0-mlogloss:0.19839
[158]	validation_0-mlogloss:0.19841
[159]	validation_0-mlogloss:0.19856
[160]	validation_0-mlogloss:0.19862
[161]	validation_0-mlogloss:0.19868
[162]	validation_0-mlogloss:0.19886
[163]	validation_0-mlogloss:0.19884
[164]	validation_0-mlogloss:0.19897
[165]	validation_0-mlogloss:0.19920
[166]	validation_0-mlogloss:0.19930
[167]	validation_0-mlogloss:0.19938
[168]	validation_0-mlogloss:0.19952
[169]	validation_0-mlogloss:0.19948
[170]	validation_0-mlogloss:0.19959
[171]	validation_0-mlogloss:0.19976
[172]	validation_0-mlogloss:0.19980
[173]	validation_0-mlogloss:0.19991
[174]	validation_0-mlogloss:0.19994
[175]	validation_0-mlogloss:0.19994
[176]	validation_0-mlogloss:0.20004
[177]	validation_0-mlogloss:0.20010
[178]	validation_0-mlogloss:0.20019
[179]	validation_0-mlogloss:0.20034
[180]	validation_0-mlogloss:0.20052
[181]	validation_0-mlogloss:0.20055
[182]	validation_0-mlogloss:0.20061
[183]	validation_0-mlogloss:0.20061
[184]	validation_0-mlogloss:0.20072
[185]	validation_0-mlogloss:0.20088
[186]	validation_0-mlogloss:0.20099
[187]	validation_0-mlogloss:0.20124
[188]	validation_0-mlogloss:0.20142
[189]	validation_0-mlogloss:0.20149
[190]	validation_0-mlogloss:0.20151
[191]	validation_0-mlogloss:0.20166
[192]	validation_0-mlogloss:0.20180
[193]	validation_0-mlogloss:0.20190
[194]	validation_0-mlogloss:0.20202
[195]	validation_0-mlogloss:0.20204
[196]	validation_0-mlogloss:0.20216
[197]	validation_0-mlogloss:0.20233
[198]	validation_0-mlogloss:0.20242
[199]	validation_0-mlogloss:0.20252

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=-1, num_class=13, ...)

In [18]:
# 8. Evaluate on validation and test sets
def print_metrics(y_true, y_pred, y_prob, set_name="Set"):
    print(f"\n=== {set_name} Metrics ===")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Macro F1-score:", f1_score(y_true, y_pred, average='macro'))
    print("Per-class report:\n", classification_report(y_true, y_pred, target_names=y_labels))

print_metrics(y_val, xgb.predict(X_val), xgb.predict_proba(X_val), "Validation")
print_metrics(y_test, xgb.predict(X_test), xgb.predict_proba(X_test), "Test")

=== Validation Metrics ===
Accuracy: 0.9059226813940202
Macro F1-score: 0.9050763863220934
Per-class report:
                                             precision    recall  f1-score   support

                  Steroid-Induced Diabetes       0.82      0.82      0.82       791
          Neonatal Diabetes Mellitus (NDM)       1.00      1.00      1.00       811
                               Prediabetic       0.98      1.00      0.99       807
                           Type 1 Diabetes       0.88      0.96      0.92       817
                          Wolfram Syndrome       0.88      0.94      0.91       797
                                      LADA       0.97      0.95      0.96       784
                           Type 2 Diabetes       0.86      0.73      0.79       810
                 Wolcott-Rallison Syndrome       0.94      0.87      0.90       810
                        Secondary Diabetes       0.82      0.76      0.79       822
Type 3c Diabetes (Pancreatogenic Diabetes)       0.81      1.00      0.90       798
                      Gestational Diabetes       0.92      0.94      0.93       802
   Cystic Fibrosis-Related Diabetes (CFRD)       0.99      0.94      0.96       820
                                      MODY       0.93      0.88      0.90       833

                                  accuracy                           0.91     10502
                                 macro avg       0.91      0.91      0.91     10502
                              weighted avg       0.91      0.91      0.90     10502


=== Test Metrics ===
Accuracy: 0.8998095238095238
Macro F1-score: 0.8988264849633553
Per-class report:
                                             precision    recall  f1-score   support

                  Steroid-Induced Diabetes       0.81      0.82      0.81       791
          Neonatal Diabetes Mellitus (NDM)       1.00      1.00      1.00       811
                               Prediabetic       0.96      1.00      0.98       806
                           Type 1 Diabetes       0.88      0.96      0.92       817
                          Wolfram Syndrome       0.89      0.94      0.92       797
                                      LADA       0.95      0.92      0.94       783
                           Type 2 Diabetes       0.85      0.72      0.78       810
                 Wolcott-Rallison Syndrome       0.94      0.89      0.91       810
                        Secondary Diabetes       0.82      0.73      0.77       822
Type 3c Diabetes (Pancreatogenic Diabetes)       0.81      1.00      0.89       798
                      Gestational Diabetes       0.89      0.93      0.91       802
   Cystic Fibrosis-Related Diabetes (CFRD)       1.00      0.91      0.95       820
                                      MODY       0.93      0.88      0.90       833

                                  accuracy                           0.90     10500
                                 macro avg       0.90      0.90      0.90     10500
                              weighted avg       0.90      0.90      0.90     10500

In [19]:
from sklearn.metrics import confusion_matrix
import plotly.figure_factory as ff

# Generate confusion matrix
cm = confusion_matrix(y_test, xgb.predict(X_test))

# Convert to DataFrame for nice display
cm_df = pd.DataFrame(cm, index=y_labels, columns=y_labels)

# Plot with Plotly
fig = ff.create_annotated_heatmap(
    z=cm_df.values,
    x=cm_df.columns.tolist(),
    y=cm_df.index.tolist(),
    colorscale='Blues',
    showscale=True,
    annotation_text=cm_df.values,
    hoverinfo='z'
)

fig.update_layout(
    title='Confusion Matrix (Test Set)',
    xaxis_title='Predicted Label',
    yaxis_title='True Label',
    autosize=False,
    width=900,
    height=900,
    margin=dict(l=200, r=50, b=150, t=100)
)
fig.update_xaxes(side="bottom")
fig.show()

## LIGHTGBM

In [20]:
import lightgbm as lgb
# LightGBM needs the same X, y as before
lgbm = lgb.LGBMClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=8,
    objective='multiclass',
    num_class=len(y_labels),
    random_state=42,
    n_jobs=-1
)

lgbm.fit(X_train, y_train, eval_set=[(X_val, y_val)])

# Evaluate
print("LightGBM Validation:")
print_metrics(y_val, lgbm.predict(X_val), None, "Validation")
print("LightGBM Test:")
print_metrics(y_test, lgbm.predict(X_test), None, "Test")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001734 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1338
[LightGBM] [Info] Number of data points in the train set: 48998, number of used features: 60
[LightGBM] [Info] Start training from score -2.585340
[LightGBM] [Info] Start training from score -2.560469
[LightGBM] [Info] Start training from score -2.566563
[LightGBM] [Info] Start training from score -2.553625
[LightGBM] [Info] Start training from score -2.577787
[LightGBM] [Info] Start training from score -2.595410
[LightGBM] [Info] Start training from score -2.562849
[LightGBM] [Info] Start training from score -2.562055
[LightGBM] [Info] Start training from score -2.547610
[LightGBM] [Info] Start training from score -2.576981
[LightGBM] [Info] Start training from score -2.572694
[LightGBM] [Info] Start training from score -2.550482
[LightGBM] [Info] Start training from score -2.534142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LightGBM Validation:

/Users/saikeerthan/NYP-AI/Year3/new_y3s1/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LGBMClassifier was fitted with feature names

=== Validation Metrics ===
Accuracy: 0.9044943820224719
Macro F1-score: 0.9036770001301822
Per-class report:
                                             precision    recall  f1-score   support

                  Steroid-Induced Diabetes       0.83      0.81      0.82       791
          Neonatal Diabetes Mellitus (NDM)       1.00      1.00      1.00       811
                               Prediabetic       0.98      1.00      0.99       807
                           Type 1 Diabetes       0.89      0.95      0.92       817
                          Wolfram Syndrome       0.88      0.93      0.91       797
                                      LADA       0.95      0.95      0.95       784
                           Type 2 Diabetes       0.85      0.74      0.79       810
                 Wolcott-Rallison Syndrome       0.93      0.87      0.90       810
                        Secondary Diabetes       0.82      0.76      0.79       822
Type 3c Diabetes (Pancreatogenic Diabetes)       0.81      1.00      0.90       798
                      Gestational Diabetes       0.92      0.93      0.92       802
   Cystic Fibrosis-Related Diabetes (CFRD)       0.99      0.94      0.96       820
                                      MODY       0.92      0.89      0.90       833

                                  accuracy                           0.90     10502
                                 macro avg       0.91      0.90      0.90     10502
                              weighted avg       0.91      0.90      0.90     10502

LightGBM Test:

/Users/saikeerthan/NYP-AI/Year3/new_y3s1/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LGBMClassifier was fitted with feature names

=== Test Metrics ===
Accuracy: 0.8998095238095238
Macro F1-score: 0.8990044471233567
Per-class report:
                                             precision    recall  f1-score   support

                  Steroid-Induced Diabetes       0.82      0.81      0.81       791
          Neonatal Diabetes Mellitus (NDM)       1.00      1.00      1.00       811
                               Prediabetic       0.96      1.00      0.98       806
                           Type 1 Diabetes       0.88      0.94      0.91       817
                          Wolfram Syndrome       0.90      0.94      0.92       797
                                      LADA       0.95      0.93      0.94       783
                           Type 2 Diabetes       0.84      0.73      0.78       810
                 Wolcott-Rallison Syndrome       0.94      0.89      0.92       810
                        Secondary Diabetes       0.81      0.75      0.77       822
Type 3c Diabetes (Pancreatogenic Diabetes)       0.81      0.99      0.89       798
                      Gestational Diabetes       0.90      0.93      0.91       802
   Cystic Fibrosis-Related Diabetes (CFRD)       1.00      0.91      0.95       820
                                      MODY       0.91      0.88      0.90       833

                                  accuracy                           0.90     10500
                                 macro avg       0.90      0.90      0.90     10500
                              weighted avg       0.90      0.90      0.90     10500

## RandomForest

In [21]:
# 1. Build the Random Forest model
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=16,
    class_weight='balanced',   # Handles any mild class imbalance
    n_jobs=-1,
    random_state=42,
    verbose=1
)

# 2. Fit the model
rf.fit(X_train, y_train)

# 3. Evaluate on validation and test sets
def print_metrics_rf(y_true, y_pred, set_name="Set"):
    print(f"\n=== {set_name} Metrics (Random Forest) ===")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Macro F1-score:", f1_score(y_true, y_pred, average='macro'))
    print("Per-class report:\n", classification_report(y_true, y_pred, target_names=y_labels))

print_metrics_rf(y_val, rf.predict(X_val), "Validation")
print_metrics_rf(y_test, rf.predict(X_test), "Test")

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.6s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:    3.0s
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:    3.2s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 200 out of 200 | elapsed:    0.1s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s

=== Validation Metrics (Random Forest) ===
Accuracy: 0.8967815654161112
Macro F1-score: 0.8955762856595051
Per-class report:
                                             precision    recall  f1-score   support

                  Steroid-Induced Diabetes       0.80      0.82      0.81       791
          Neonatal Diabetes Mellitus (NDM)       1.00      1.00      1.00       811
                               Prediabetic       0.93      1.00      0.96       807
                           Type 1 Diabetes       0.85      1.00      0.92       817
                          Wolfram Syndrome       0.85      1.00      0.92       797
                                      LADA       0.93      0.95      0.94       784
                           Type 2 Diabetes       0.90      0.72      0.80       810
                 Wolcott-Rallison Syndrome       1.00      0.83      0.91       810
                        Secondary Diabetes       0.82      0.75      0.78       822
Type 3c Diabetes (Pancreatogenic Diabetes)       0.79      1.00      0.89       798
                      Gestational Diabetes       0.91      0.87      0.89       802
   Cystic Fibrosis-Related Diabetes (CFRD)       0.99      0.87      0.93       820
                                      MODY       0.94      0.85      0.89       833

                                  accuracy                           0.90     10502
                                 macro avg       0.90      0.90      0.90     10502
                              weighted avg       0.90      0.90      0.90     10502


=== Test Metrics (Random Forest) ===
Accuracy: 0.8894285714285715
Macro F1-score: 0.8879229751934384
Per-class report:
                                             precision    recall  f1-score   support

                  Steroid-Induced Diabetes       0.79      0.82      0.81       791
          Neonatal Diabetes Mellitus (NDM)       1.00      1.00      1.00       811
                               Prediabetic       0.93      1.00      0.96       806
                           Type 1 Diabetes       0.85      1.00      0.92       817
                          Wolfram Syndrome       0.86      0.99      0.92       797
                                      LADA       0.92      0.94      0.93       783
                           Type 2 Diabetes       0.87      0.69      0.77       810
                 Wolcott-Rallison Syndrome       0.98      0.85      0.91       810
                        Secondary Diabetes       0.81      0.73      0.77       822
Type 3c Diabetes (Pancreatogenic Diabetes)       0.78      1.00      0.88       798
                      Gestational Diabetes       0.90      0.87      0.88       802
   Cystic Fibrosis-Related Diabetes (CFRD)       1.00      0.85      0.92       820
                                      MODY       0.93      0.84      0.89       833

                                  accuracy                           0.89     10500
                                 macro avg       0.89      0.89      0.89     10500
                              weighted avg       0.89      0.89      0.89     10500

[Parallel(n_jobs=8)]: Done 200 out of 200 | elapsed:    0.1s finished

# Deep Learning

In [22]:
import tensorflow as tf 
from tensorflow import keras

In [23]:
# 2. Column definitions
target_col = 'Target'
categorical_cols = [
    'Genetic Markers', 'Autoantibodies', 'Family History', 'Environmental Factors', 
    'Physical Activity', 'Dietary Habits', 'Ethnicity', 'Socioeconomic Factors', 
    'Smoking Status', 'Alcohol Consumption', 'Glucose Tolerance Test', 
    'History of PCOS', 'Previous Gestational Diabetes', 'Pregnancy History', 
    'Cystic Fibrosis Diagnosis', 'Steroid Use History', 'Genetic Testing', 
    'Neurological Assessments', 'Liver Function Tests', 'Urine Test', 'Early Onset Symptoms'
]
numerical_cols = [
    'Insulin Levels', 'Age', 'BMI', 'Blood Pressure', 'Cholesterol Levels',
    'Waist Circumference', 'Blood Glucose Levels', 'Birth Weight',
    'Weight Gain During Pregnancy', 'Pancreatic Health', 'Pulmonary Function',
    'Digestive Enzyme Levels'
]

In [24]:
# 3. Encode target
y = df[target_col].astype(str)
y_cat, y_labels = pd.factorize(y)  # y_labels saves the mapping
num_classes = len(y_labels)

# 4. Preprocessing - Encoding
# -- Categorical features: OneHot
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_cat = ohe.fit_transform(df[categorical_cols])

# -- Numerical features: StandardScaler
scaler = StandardScaler()
X_num = scaler.fit_transform(df[numerical_cols])

# -- Concatenate
X = np.hstack([X_num, X_cat])

In [25]:
# 5. Train/val/test split (same as before)
X_temp, X_test, y_temp, y_test = train_test_split(X, y_cat, test_size=0.15, random_state=42, stratify=y_cat)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.1765, random_state=42, stratify=y_temp)

# 6. To categorical (one-hot targets for Keras)
y_train_oh = keras.utils.to_categorical(y_train, num_classes)
y_val_oh   = keras.utils.to_categorical(y_val, num_classes)
y_test_oh  = keras.utils.to_categorical(y_test, num_classes)

In [26]:
model = keras.Sequential([
    keras.layers.Input(shape=(X_train.shape[1],)),
    keras.layers.Dense(512, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(num_classes, activation='softmax')
])

In [27]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 512)            │        31,232 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 13)             │         1,677 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 200,717 (784.05 KB)

 Trainable params: 198,925 (777.05 KB)

 Non-trainable params: 1,792 (7.00 KB)

In [28]:
# 8. Train model
early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
history = model.fit(
    X_train, y_train_oh,
    epochs=50,
    batch_size=1024,
    validation_data=(X_val, y_val_oh),
    callbacks=[early_stop],
    verbose=2
)

Epoch 1/50
48/48 - 2s - 44ms/step - accuracy: 0.5446 - loss: 1.2731 - val_accuracy: 0.7035 - val_loss: 1.1174
Epoch 2/50
48/48 - 1s - 17ms/step - accuracy: 0.7049 - loss: 0.7357 - val_accuracy: 0.6896 - val_loss: 0.9149
Epoch 3/50
48/48 - 1s - 20ms/step - accuracy: 0.7277 - loss: 0.6759 - val_accuracy: 0.7010 - val_loss: 0.8053
Epoch 4/50
48/48 - 1s - 19ms/step - accuracy: 0.7449 - loss: 0.6281 - val_accuracy: 0.7199 - val_loss: 0.7256
Epoch 5/50
48/48 - 1s - 19ms/step - accuracy: 0.7571 - loss: 0.5998 - val_accuracy: 0.7566 - val_loss: 0.6388
Epoch 6/50
48/48 - 1s - 19ms/step - accuracy: 0.7684 - loss: 0.5756 - val_accuracy: 0.7673 - val_loss: 0.5946
Epoch 7/50
48/48 - 1s - 19ms/step - accuracy: 0.7746 - loss: 0.5557 - val_accuracy: 0.7764 - val_loss: 0.5635
Epoch 8/50
48/48 - 1s - 19ms/step - accuracy: 0.7811 - loss: 0.5371 - val_accuracy: 0.7908 - val_loss: 0.5257
Epoch 9/50
48/48 - 1s - 20ms/step - accuracy: 0.7898 - loss: 0.5214 - val_accuracy: 0.8053 - val_loss: 0.4948
Epoch 10/50
48/48 - 1s - 19ms/step - accuracy: 0.7936 - loss: 0.5100 - val_accuracy: 0.8013 - val_loss: 0.5000
Epoch 11/50
48/48 - 1s - 18ms/step - accuracy: 0.7998 - loss: 0.4947 - val_accuracy: 0.8106 - val_loss: 0.4786
Epoch 12/50
48/48 - 1s - 19ms/step - accuracy: 0.8048 - loss: 0.4824 - val_accuracy: 0.8139 - val_loss: 0.4669
Epoch 13/50
48/48 - 1s - 19ms/step - accuracy: 0.8111 - loss: 0.4749 - val_accuracy: 0.8240 - val_loss: 0.4482
Epoch 14/50
48/48 - 1s - 19ms/step - accuracy: 0.8111 - loss: 0.4634 - val_accuracy: 0.8213 - val_loss: 0.4515
Epoch 15/50
48/48 - 1s - 19ms/step - accuracy: 0.8146 - loss: 0.4573 - val_accuracy: 0.8278 - val_loss: 0.4417
Epoch 16/50
48/48 - 1s - 19ms/step - accuracy: 0.8183 - loss: 0.4481 - val_accuracy: 0.8283 - val_loss: 0.4344
Epoch 17/50
48/48 - 1s - 19ms/step - accuracy: 0.8247 - loss: 0.4353 - val_accuracy: 0.8266 - val_loss: 0.4378
Epoch 18/50
48/48 - 1s - 19ms/step - accuracy: 0.8233 - loss: 0.4329 - val_accuracy: 0.8282 - val_loss: 0.4343
Epoch 19/50
48/48 - 1s - 19ms/step - accuracy: 0.8278 - loss: 0.4276 - val_accuracy: 0.8299 - val_loss: 0.4243
Epoch 20/50
48/48 - 1s - 19ms/step - accuracy: 0.8294 - loss: 0.4208 - val_accuracy: 0.8317 - val_loss: 0.4254
Epoch 21/50
48/48 - 1s - 19ms/step - accuracy: 0.8319 - loss: 0.4161 - val_accuracy: 0.8350 - val_loss: 0.4116
Epoch 22/50
48/48 - 1s - 19ms/step - accuracy: 0.8358 - loss: 0.4097 - val_accuracy: 0.8345 - val_loss: 0.4152
Epoch 23/50
48/48 - 1s - 19ms/step - accuracy: 0.8362 - loss: 0.4037 - val_accuracy: 0.8380 - val_loss: 0.4101
Epoch 24/50
48/48 - 1s - 20ms/step - accuracy: 0.8385 - loss: 0.3983 - val_accuracy: 0.8360 - val_loss: 0.4092
Epoch 25/50
48/48 - 1s - 19ms/step - accuracy: 0.8389 - loss: 0.3953 - val_accuracy: 0.8388 - val_loss: 0.4022
Epoch 26/50
48/48 - 1s - 19ms/step - accuracy: 0.8415 - loss: 0.3903 - val_accuracy: 0.8401 - val_loss: 0.3997
Epoch 27/50
48/48 - 1s - 19ms/step - accuracy: 0.8436 - loss: 0.3850 - val_accuracy: 0.8411 - val_loss: 0.3969
Epoch 28/50
48/48 - 1s - 19ms/step - accuracy: 0.8436 - loss: 0.3784 - val_accuracy: 0.8429 - val_loss: 0.3926
Epoch 29/50
48/48 - 1s - 19ms/step - accuracy: 0.8474 - loss: 0.3765 - val_accuracy: 0.8412 - val_loss: 0.3963
Epoch 30/50
48/48 - 1s - 19ms/step - accuracy: 0.8471 - loss: 0.3754 - val_accuracy: 0.8404 - val_loss: 0.3913
Epoch 31/50
48/48 - 1s - 19ms/step - accuracy: 0.8490 - loss: 0.3712 - val_accuracy: 0.8425 - val_loss: 0.3938
Epoch 32/50
48/48 - 1s - 19ms/step - accuracy: 0.8519 - loss: 0.3639 - val_accuracy: 0.8440 - val_loss: 0.3851
Epoch 33/50
48/48 - 1s - 19ms/step - accuracy: 0.8529 - loss: 0.3604 - val_accuracy: 0.8448 - val_loss: 0.3858
Epoch 34/50
48/48 - 1s - 19ms/step - accuracy: 0.8539 - loss: 0.3573 - val_accuracy: 0.8415 - val_loss: 0.3825
Epoch 35/50
48/48 - 1s - 23ms/step - accuracy: 0.8548 - loss: 0.3559 - val_accuracy: 0.8453 - val_loss: 0.3847
Epoch 36/50
48/48 - 1s - 22ms/step - accuracy: 0.8550 - loss: 0.3517 - val_accuracy: 0.8426 - val_loss: 0.3787
Epoch 37/50
48/48 - 1s - 21ms/step - accuracy: 0.8563 - loss: 0.3497 - val_accuracy: 0.8462 - val_loss: 0.3817
Epoch 38/50
48/48 - 1s - 21ms/step - accuracy: 0.8579 - loss: 0.3477 - val_accuracy: 0.8418 - val_loss: 0.3794
Epoch 39/50
48/48 - 1s - 20ms/step - accuracy: 0.8599 - loss: 0.3416 - val_accuracy: 0.8487 - val_loss: 0.3734
Epoch 40/50
48/48 - 1s - 23ms/step - accuracy: 0.8600 - loss: 0.3404 - val_accuracy: 0.8488 - val_loss: 0.3756
Epoch 41/50
48/48 - 1s - 21ms/step - accuracy: 0.8623 - loss: 0.3371 - val_accuracy: 0.8475 - val_loss: 0.3797
Epoch 42/50
48/48 - 1s - 20ms/step - accuracy: 0.8635 - loss: 0.3335 - val_accuracy: 0.8450 - val_loss: 0.3810
Epoch 43/50
48/48 - 1s - 24ms/step - accuracy: 0.8631 - loss: 0.3324 - val_accuracy: 0.8482 - val_loss: 0.3705
Epoch 44/50
48/48 - 1s - 21ms/step - accuracy: 0.8667 - loss: 0.3272 - val_accuracy: 0.8471 - val_loss: 0.3726
Epoch 45/50
48/48 - 2s - 32ms/step - accuracy: 0.8670 - loss: 0.3249 - val_accuracy: 0.8521 - val_loss: 0.3690
Epoch 46/50
48/48 - 1s - 25ms/step - accuracy: 0.8682 - loss: 0.3207 - val_accuracy: 0.8481 - val_loss: 0.3712
Epoch 47/50
48/48 - 1s - 25ms/step - accuracy: 0.8703 - loss: 0.3173 - val_accuracy: 0.8496 - val_loss: 0.3699
Epoch 48/50
48/48 - 1s - 23ms/step - accuracy: 0.8715 - loss: 0.3149 - val_accuracy: 0.8526 - val_loss: 0.3675
Epoch 49/50
48/48 - 1s - 26ms/step - accuracy: 0.8693 - loss: 0.3164 - val_accuracy: 0.8539 - val_loss: 0.3657
Epoch 50/50
48/48 - 1s - 20ms/step - accuracy: 0.8722 - loss: 0.3115 - val_accuracy: 0.8489 - val_loss: 0.3795

In [29]:
# 9. Evaluate
def print_dl_metrics(y_true, y_pred, set_name="Set"):
    print(f"\n=== {set_name} Metrics (Deep Learning) ===")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Macro F1-score:", f1_score(y_true, y_pred, average='macro'))
    print("Per-class report:\n", classification_report(y_true, y_pred, target_names=y_labels))

y_val_pred = np.argmax(model.predict(X_val), axis=1)
y_test_pred = np.argmax(model.predict(X_test), axis=1)

print_dl_metrics(y_val, y_val_pred, "Validation")
print_dl_metrics(y_test, y_test_pred, "Test")

329/329 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
329/329 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step

=== Validation Metrics (Deep Learning) ===
Accuracy: 0.8539325842696629
Macro F1-score: 0.8532013884484113
Per-class report:
                                             precision    recall  f1-score   support

                  Steroid-Induced Diabetes       0.81      0.71      0.76       791
          Neonatal Diabetes Mellitus (NDM)       1.00      1.00      1.00       811
                               Prediabetic       0.88      0.97      0.92       807
                           Type 1 Diabetes       0.87      0.89      0.88       817
                          Wolfram Syndrome       0.86      0.93      0.89       797
                                      LADA       0.91      0.86      0.89       784
                           Type 2 Diabetes       0.85      0.70      0.77       810
                 Wolcott-Rallison Syndrome       0.92      0.84      0.88       810
                        Secondary Diabetes       0.77      0.75      0.76       822
Type 3c Diabetes (Pancreatogenic Diabetes)       0.71      0.94      0.81       798
                      Gestational Diabetes       0.82      0.83      0.82       802
   Cystic Fibrosis-Related Diabetes (CFRD)       0.94      0.83      0.88       820
                                      MODY       0.83      0.85      0.84       833

                                  accuracy                           0.85     10502
                                 macro avg       0.86      0.85      0.85     10502
                              weighted avg       0.86      0.85      0.85     10502


=== Test Metrics (Deep Learning) ===
Accuracy: 0.8420952380952381
Macro F1-score: 0.841431325575779
Per-class report:
                                             precision    recall  f1-score   support

                  Steroid-Induced Diabetes       0.78      0.70      0.74       791
          Neonatal Diabetes Mellitus (NDM)       1.00      1.00      1.00       811
                               Prediabetic       0.87      0.95      0.91       806
                           Type 1 Diabetes       0.85      0.88      0.86       817
                          Wolfram Syndrome       0.86      0.94      0.90       797
                                      LADA       0.90      0.84      0.87       783
                           Type 2 Diabetes       0.83      0.70      0.76       810
                 Wolcott-Rallison Syndrome       0.94      0.85      0.89       810
                        Secondary Diabetes       0.78      0.69      0.73       822
Type 3c Diabetes (Pancreatogenic Diabetes)       0.68      0.94      0.79       798
                      Gestational Diabetes       0.79      0.81      0.80       802
   Cystic Fibrosis-Related Diabetes (CFRD)       0.94      0.80      0.87       820
                                      MODY       0.80      0.85      0.82       833

                                  accuracy                           0.84     10500
                                 macro avg       0.85      0.84      0.84     10500
                              weighted avg       0.85      0.84      0.84     10500

# ENSEMBLING

wip